apiVersion: apps/v1
kind: Deployment
metadata:
  name: elastichsearch
spec:
  selector:
    matchLabels:
      run: elastichsearch
  replicas: 2
  template:
    metadata:
      labels:
        run: elastichsearch
    spec:
      containers:
        - name: elastichsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:6.4.3
          imagePullPolicy: Always
          env:
          #- name: SERVER_URL
          #  value: jdbc:postgresql://100.66.104.225:5432/xiaobaobaodb
          #- name: SERVER_USR
          #  value: postgres
          #- name: SERVER_PWD
          #  value: abcd1234
      #imagePullSecrets:
      #  - name: regcred