apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
spec:
  selector:
    matchLabels:
      run: elasticsearch
  replicas: 2
  template:
    metadata:
      labels:
        run: elasticsearch
    spec:
      containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:6.4.3
          imagePullPolicy: Always
      #imagePullSecrets:
      #  - name: regcred